# Generated by Django 2.1.3 on 2019-01-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartManager',
        ),
    ]
